apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kitchensvc
  labels:
    {{- include "restaurant-svc.labels" . | nindent 4 }}
spec:
  #TODO implement 'port', 'type', 'targetPort' here. Leverage the properties we defined in Values.yaml.
  type: LoadBalancer
  ports:
    - port: 8764
      targetPort: 8764
      protocol: TCP
      name: http
  selector:
    app: kitchensvc
#    #TODO implement proper selector here to bind this service and kitchensvc pods.
#    app: s
